# Generated by Django 4.1.7 on 2023-04-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_prompts_age_prompts_message_count_prompts_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompts',
            old_name='prompt',
            new_name='personality',
        ),
    ]
